### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by Pragya2056** [HarshitSati/Basic_c-plus-plus_programs#27]
The Readme could be more updated with the mention of: -
1. What is hacktoberfest?
2. What is the repo requirements?
3. How to contribute?
4. The rules
5. The Code of Conduct
6. Contributors mention

Please assign me in the issue and I will prepare a documentation on this.

**Comment by HarshitSati** [comment]
Hi Pragya, assigned you on the issue, let me know if you need anything else

**Comment by Pragya2056** [comment]
#31 
The commit is made
